### ISSUE TITLE
Exception Error when trying to run commands in Spigot:

### ISSUE THREAD

**Issue by darkphan** [LasaJoniHD/WildRTP#11]
When trying to run the /rtp (or have it run on first join) you get the following error: (this is in mc 1.20.2, spigot version: 3897-Spigot-a0f3d48-99aafc2 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT))

`[2023-09-30 19:59:53] [Thread-10/WARN]: Exception in thread "Thread-10" java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component[2023-09-30 19:59:53] [Thread-10/WARN]: at [joni.utils.MoveTimer$1.run](http://joni.utils.movetimer%241.run/)([MoveTimer.java:25](http://movetimer.java:25/))[2023-09-30 19:59:53] [Thread-10/WARN]: Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component[2023-09-30 19:59:53] [Thread-10/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0([PluginClassLoader.java:147](http://pluginclassloader.java:147/))[2023-09-30 19:59:53] [Thread-10/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass([PluginClassLoader.java:99](http://pluginclassloader.java:99/))[2023-09-30 19:59:53] [Thread-10/WARN]: at java.base/java.lang.ClassLoader.loadClass([ClassLoader.java:520](http://classloader.java:520/))[2023-09-30 19:59:53] [Thread-10/WARN]: ... 1 more`

**Comment by darkphan** [comment]
Switching over to paper resolves the issue.

**Comment by LasaJoniHD** [comment]
I will look into it, however I think paper is way better than spigot.

**Comment by LasaJoniHD** [comment]
Marked as only compatible with paper

**Comment by LasaJoniHD** [comment]
Spigot compatibility with version 2.1
