### ISSUE TITLE
[REQUEST] Create a plataform underneath the player if no blocks are found.

### ISSUE THREAD

**Issue by lnxredir** [LasaJoniHD/WildRTP#12]
Thanks for making this awesome plugins in the first place, the only one still in development that just does the thing it needs to! Title pretty much says everything, I play in a lot of void worlds (skyblock and such) so I was looking for a way to generate a platform of about 3x3 underneath the player when they use the /rtp cmd. If possible add a variable on the config file to alter the block of the platform and the size. Also if possible, set the allowed height of the platform, making it a fixed or random Y coordinate.

**Comment by LasaJoniHD** [comment]
Thank you for using my plugin. However, I am unsure if the average user would find this option helpful or if it would cause confusion. Therefore, I do not believe it makes sense to add this request. I could create a new branch with this feature added. What do you think?

**Comment by lnxredir** [comment]
I would love that, I know the average player wont find this feature useful but there's no plugin that currently does that (an RTP/wild plugin, theres quite a lot of /island or skyblock plugins to provide the functionality but they're limited to a specific type of gamemode)

**Comment by LasaJoniHD** [comment]
Hello, Unfortunately I had not much time last week. However today I can say that your plugin is done. It creates a 3x3 platform with a fixed y with the block you like. You can download it on github. https://github.com/LasaJoniHD/WildRTP/releases/tag/v2.1
I called it voidrtp

**Comment by lnxredir** [comment]
Hey! Sorry to bother you, the link for this change is gone, you think you can upload it again please? Or create a new branch and I'll fork it. Cheers!
