### ISSUE TITLE
[VoidRTP] VoidRTP.jar is not available for download

### ISSUE THREAD

**Issue by lnxredir** [LasaJoniHD/WildRTP#13]
Hey! Sorry to bother you, the link for the VoidRTP plugin is gone, you think you can upload it again please? Or create a new branch and I'll fork it. Cheers!

**Comment by LasaJoniHD** [comment]
Hey, sorry for the late reply. I think I found the plugin on my computer, I also created a fork. But this version is the old 2.1, not the new 2.5. You can download it from https://github.com/LasaJoniHD/WildRTP/releases/tag/v2.1
